services:
  solr:
    build:
      context: .
      dockerfile: Dockerfile
    user: "150:150"
    read_only: true
    environment:
      SOLR_HOME: /var/solr/data
      SOLR_JAVA_MEM: -Xms512m -Xmx512m
    ports:
      - "8983:8983"
    volumes:
      - solr-var:/var/solr
    tmpfs:
      - /tmp:size=256m,uid=150,gid=150,mode=1777

volumes:
  solr-var:
